"""Add defense model

Revision ID: 87abaacf97c7
Revises: 20eeb20bc96d
Create Date: 2025-07-31 16:42:19.497728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87abaacf97c7'
down_revision = '20eeb20bc96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defense')
    # ### end Alembic commands ###
